alamo_sf_link: https://www.drafthouse.com/sf?showCalendar=true
alamo_la_link: https://www.drafthouse.com/los-angeles?showCalendar=true

amc_sunval_link: https://www.amctheatres.com/movie-theatres/san-francisco/amc-dine-in-sunnyvale-12/showtimes?date=
amc_mercado_link: https://www.amctheatres.com/movie-theatres/san-francisco/amc-mercado-20/showtimes?date=
amc_metreon_link: 
amc_kabuki_link:
amc_baystreet_link:
